[project]
name = "wetlinks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.118.0",
    "uvicorn>=0.23.2",
    "jinja2>=3.1.6",
    "requests>=2.32.5"
]
